import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, MapPin, Phone, Siren } from "lucide-react";
import PageHeading from "@/components/PageHeading";
import { HOSPITAL } from "@/data/hospital";

export const metadata: Metadata = { title: "Emergency" };

export default function EmergencyPage() {
  return <><PageHeading eyebrow="EMERGENCY INFORMATION" title="Urgent help, day or night" description="If someone is in immediate danger, contact local emergency services or go to the nearest emergency department. The contact details below are demo placeholders; verify them before relying on them." /><section className="container-custom py-10 md:py-14"><div className="grid gap-8 lg:grid-cols-[1fr_0.85fr]"><div className="rounded-2xl border border-red-200 bg-emergency-50 p-6 md:p-8"><div className="flex items-center gap-3 text-emergency-700"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-white"><Siren size={22} /></span><span className="text-sm font-semibold">Emergency line · listed 24/7</span></div><p className="mt-5 text-sm text-ink-500">Call the hospital emergency number</p><a href={`tel:${HOSPITAL.phoneEmergencyTel}`} className="mt-1 inline-flex min-h-12 items-center gap-2 text-2xl font-bold text-emergency-700"><Phone size={22} />{HOSPITAL.phoneEmergency}</a><p className="mt-4 text-sm leading-6 text-ink-500">This number is a placeholder and may not connect. Confirm the current emergency contact with hospital management.</p></div><div className="rounded-2xl border border-line p-6"><h2 className="text-xl font-bold">Before you travel</h2><ul className="mt-4 space-y-3 text-sm leading-6 text-ink-700"><li className="flex gap-2"><Check size={17} className="mt-0.5 shrink-0 text-primary-700" />Call ahead when possible to confirm service availability.</li><li className="flex gap-2"><Check size={17} className="mt-0.5 shrink-0 text-primary-700" />Bring current prescriptions, allergy information, and relevant medical records.</li><li className="flex gap-2"><Check size={17} className="mt-0.5 shrink-0 text-primary-700" />Ask someone to accompany the patient when practical.</li></ul></div></div><div className="mt-8 flex flex-wrap gap-3"><Link href="/contact" className="inline-flex h-11 items-center gap-2 rounded-xl bg-primary-600 px-4 font-semibold text-white">Location and directions <MapPin size={17} /></Link><Link href="/services" className="inline-flex h-11 items-center gap-2 rounded-xl border border-primary-600 px-4 font-semibold text-primary-700">View services <ArrowRight size={16} /></Link></div></section></>;
}